### ISSUE TITLE
Parent interface on databases

### ISSUE THREAD

**Issue by tspoke** [florent37/RxAndroidOrm#1]
Hi Florent,

I wanted to implements a version of [store2store](https://github.com/playmoweb/store2store) with your orm. For now I have an issue with your generated code of ObjectDatabase.

To extends and use correctly your library a common interface between databases is needed. 

Something like : 

```java
public interface Database<T> {
    QueryBuilder select(final T object);    
    
    Observable<T> add(final T object);

    Observable<List<T>> add(final List<T> objects);

    Observable<T> update(final T object);

    Observable<List<T>> update(final List<T> objects);

    Observable<Boolean> exists(SQLiteDatabase db, final T object); // It should be possible to remove the SQLiteDatabase param here :)

    Observable<Boolean> delete(final T object);

    Observable<Boolean> delete(final List<T> objects);

    Observable<Boolean> deleteAll();

    Observable<Integer> count();
}
```

Then in the generated class : 

```java
public class ComputerDatabase extends Database<Computer> {
 // ...
}
```

Let the generated Databases classes implementing this interface could help us to abstract a little bit more our code and do not depends on concretes classes.

If you want me to do a pull request for that, let me know ;)

Thank you,
Thibaud.

**Comment by florent37** [comment]
Yes it's a good idea 👍 
you want to try to make a pull request ?

**Comment by florent37** [comment]
The problem could come from the QueryBuilder, it has different methods depending on the model class

**Comment by tspoke** [comment]
Ok, I will have a look and try something (even if I'm not familiar with rxjava v2) :)

**Comment by florent37** [comment]
but what's the issue you had on your project ? it's just because you tried
to generify it ?


2017-05-09 16:58 GMT+02:00 Thibaud Giovannetti <notifications@github.com>:

**Comment by florent37** [comment]
you can generify the 
```
public interface Database<T> {    
    Observable<T> add(final T object);

    Observable<List<T>> add(final List<T> objects);

    Observable<T> update(final T object);

    Observable<List<T>> update(final List<T> objects);

    Observable<Boolean> exists(SQLiteDatabase db, final T object); // It should be possible to remove the SQLiteDatabase param here :)

    Observable<Boolean> delete(final T object);

    Observable<Boolean> delete(final List<T> objects);

    Observable<Boolean> deleteAll();

    Observable<Integer> count();
}
```

but the Query will be hard to generify

**Comment by tspoke** [comment]
In my project I use generics and I need to create an abstract DAO which use only basic operations (CRUD) from your database object. For the moment you don't have a common interface and I can't do things like : 

```
private final Database<T> abstractDatabase; // set in constructor

public Observable<T> example() {
    return abstractDatabase.select()
                .label().equalsTo("MasterRace");
}

```

Let me take a look this evening ;)

**Comment by florent37** [comment]
the `.label()` is only generated if the object has a "label" attribute
but we can add generic method, like,

`field("label", String.class).equalsTo("MasterRace")`

**Comment by florent37** [comment]
Thanks a lot for the pull request, 
I sent a v1.0.1 ;)

**Comment by tspoke** [comment]
@florent37 you are welcome ;)

I will try it tomorrow with my library \o/ 

**Thank you !**
