### ISSUE TITLE
Cannot get 1.0.1

### ISSUE THREAD

**Issue by tspoke** [florent37/RxAndroidOrm#3]
Hi @florent37,

I can't get the library v1.0.1 on gradle anymore. There is probably an issue in your publish conf.

```
Error:Failed to resolve: annotationProcessor
```

**Another issue** 

It looks like the Database interface added in #2 (and all the static java files) are not generated if there is no @Model annotations in models. I didn't see it yesterday. It could be interesting to generate these files no matter if this annotation is used. 
IMHO, these statics java classes could be created in your library directly (and not generated) to improve maintainability.

Thank you ;)

**Comment by florent37** [comment]
yes we should generate it if an @Model contains a one to many of this object

**Comment by florent37** [comment]
and try with the `1.0.2`

I don't know why, but the 1.0.1 is buggy...

**Comment by tspoke** [comment]
Working with 1.0.2 ;)
